#!/bin/bash

MICRONETS_GW_SERVICE_DIR=/opt/micronets-gw/
MICRONETS_GW_VIRTENV_NAME=virtualenv


function hr {
  echo "------------------------------------------------------------------------------------------------------"
}

function link_ifupdown {
  rm /etc/network/if-pre-up.d/openvswitch > /dev/null 2>&1
  rm /etc/network/if-post-down.d/openvswitch > /dev/null 2>&1
  ln -s ${MICRONETS_GW_SERVICE_DIR}/bin/ifupdown.sh /etc/network/if-pre-up.d/micronets-gw-openvswitch > /dev/null 2>&1
  ln -s ${MICRONETS_GW_SERVICE_DIR}/bin/ifupdown.sh /etc/network/if-post-down.d/micronets-gw-openvswitch > /dev/null 2>&1
}

function install-ovs-bootstrap-service {
  echo "Reloading service files."
  systemctl daemon-reload
  echo "Starting ovs-bootstrap service."
  systemctl start ovs-bootstrap.service
}

function install-gw-service {
  pushd ${MICRONETS_GW_SERVICE_DIR} > /dev/null
  echo "Creating virtualenv ${MICRONETS_GW_VIRTENV_NAME} (in ${MICRONETS_GW_SERVICE_DIR}/${MICRONETS_GW_VIRTENV_NAME})"
  virtualenv --clear -p $(which python3.6) ${MICRONETS_GW_SERVICE_DIR}/${MICRONETS_GW_VIRTENV_NAME}
  source $MICRONETS_GW_VIRTENV_NAME/bin/activate
  echo "Running: pip install -r requirements.txt"
  pip install -r requirements.txt
  popd > /dev/null
  echo "Installing micronets-gw service."
  mv ${MICRONETS_GW_SERVICE_DIR}/micronets-gw.service /lib/systemd/system > /dev/null 2>&1
  echo "Reloading service files."
  systemctl daemon-reload
  echo "Enabling micronets-gw service."
  systemctl enable micronets-gw.service
  echo "Starting micronets-gw service."
  systemctl start micronets-gw.service
}

function main {
  {
    echo "POSTINSTALL: ${TAG}"
    link_ifupdown
    install-ovs-bootstrap-service
    install-gw-service
  } 2>&1 | logger -t ${TAG}
}

TS=`date +%j'T'%H%M%S`
TAG="mngw-post-${TS}"
if [ ! -z "${2}" ]; then
  echo "Upgrading from version ${2}"
fi
main
grep "${TAG}" /var/log/syslog
exit 0

