#!/bin/bash

function hr {
  echo "------------------------------------------------------------------------------------------------------"
}

function link_ifupdown {
  rm /etc/network/if-pre-up.d/openvswitch > /dev/null 2>&1
  rm /etc/network/if-post-down.d/openvswitch > /dev/null 2>&1
  ln -s /opt/micronets-gw/bin/ifupdown.sh /etc/network/if-pre-up.d/micronets-gw-openvswitch > /dev/null 2>&1
  ln -s /opt/micronets-gw/bin/ifupdown.sh /etc/network/if-post-down.d/micronets-gw-openvswitch > /dev/null 2>&1
}

function install-ovs-bootstrap-service {
  echo "Reloading service files."
  systemctl daemon-reload
  echo "Starting ovs-bootstrap service."
  systemctl start ovs-bootstrap.service
}

function install-gw-service {
  echo "Installing micronets-gw service."
  mv /opt/micronets-gw/micronets-gw.service /lib/systemd/system > /dev/null 2>&1
  echo "Reloading service files."
  systemctl daemon-reload
  echo "Enabling micronets-gw service."
  systemctl enable micronets-gw.service
  echo "Starting micronets-gw service."
  systemctl start micronets-gw.service
}

function main {
  {
    echo "POSTINSTALL: ${TAG}"
    link_ifupdown
    install-ovs-bootstrap-service
    install-gw-service
  } 2>&1 | logger -t ${TAG}
}

TS=`date +%j'T'%H%M%S`
TAG="mngw-post-${TS}"
if [ ! -z "${2}" ]; then
  echo "Upgrading from version ${2}"
fi
main
grep "${TAG}" /var/log/syslog
exit 0

